development:

  #ROLES 
  rol_administrador: 1
  rol_operador: 3
  rol_super: 6
  
  #sistemas
  sistema_RUE: 1
  
  #TIPOS ELEMENTOS INTERFAZ
  radio_button: 1
  check_box: 2
  text: 3
  combo_box: 4
  
  #TIPOS DATO
  tipo_dato_numerico: 1
  tipo_dato_texto: 2
 
  #TIPOS DOCUMENTOS
  certificado_nacimiento: 6
  sin_documento: 5
  cedula_identidad: 1

  #SEXOS GANADOS
  sexo_ganado_macho: 1
  sexo_ganado_hembra: 2

  #controles
  control_vacunacion: 1
  control_sales: 2
  control_reconstituyente: 3
  control_interno: 4
  control_externo: 5
  control_antibiotico: 6
  control_peso: 7

  #TIPOS RESOLUCIONES DOCUMENTOS
  tipo_resolucion_control_ganado: 1

  #ESTADOS CELOS
  estado_celo_en_celo_activo: 1
  estado_celo_en_reproduccion: 2
  estado_celo_en_perdido: 3

  #ESTADOS GANADOS
  estado_ganado_activo: 1
  estado_ganado_inactivo: 2
  estado_ganado_en_celo: 3
  estado_ganado_en_reproduccion: 4

  #ETAPAS GANADOS
  etapa_ganado_torito: 4
  etapa_ganado_toro: 7

  #TIPOS CONCEPCIONES
  tipo_concepcion_monta_natural: 1
  tipo_concepcion_inseminacion_artificial: 2

  #ESTADOS REPRODUCCIONES
  estado_reproduccion_proceso_fecundacion: 1
  estado_reproduccion_prenhez: 2
  estado_reproduccion_finalizado: 3
  estado_reproduccion_perdido: 4
 
  

production:

  #ROLES 
  rol_administrador: 1
  rol_operador: 3
  rol_super: 6
   
  #sistemas
  sistema_RUE: 1
  
  #TIPOS ELEMENTOS INTERFAZ
  radio_button: 1
  check_box: 2
  text: 3
  combo_box: 4
  
  #TIPOS DATO
  tipo_dato_numerico: 1
  tipo_dato_texto: 2
 
  #TIPOS DOCUMENTOS
  certificado_nacimiento: 6
  sin_documento: 5
  cedula_identidad: 1

  #SEXOS GANADOS
  sexo_ganado_macho: 1
  sexo_ganado_hembra: 2

  #controles
  control_vacunacion: 1
  control_sales: 2
  control_reconstituyente: 3
  control_interno: 4
  control_externo: 5
  control_antibiotico: 6
  control_peso: 7

  #TIPOS RESOLUCIONES DOCUMENTOS
  tipo_resolucion_control_ganado: 1

  #ESTADOS CELOS
  estado_celo_en_celo_activo: 1
  estado_celo_en_reproduccion: 2
  estado_celo_en_perdido: 3

  #ESTADOS GANADOS
  estado_ganado_activo: 1
  estado_ganado_inactivo: 2
  estado_ganado_en_celo: 3
  estado_ganado_en_reproduccion: 4

  #ETAPAS GANADOS
  etapa_ganado_torito: 4
  etapa_ganado_toro: 7

  #TIPOS CONCEPCIONES
  tipo_concepcion_monta_natural: 1
  tipo_concepcion_inseminacion_artificial: 2

  #ESTADOS REPRODUCCIONES
  estado_reproduccion_proceso_fecundacion: 1
  estado_reproduccion_prenhez: 2
  estado_reproduccion_finalizado: 3
  estado_reproduccion_perdido: 4
  
  