development:

  #ROLES 
  rol_administrador: 1
  rol_operador: 3
  rol_super: 6
  
  #sistemas
  sistema_RUE: 1
  
  #TIPOS ELEMENTOS INTERFAZ
  radio_button: 1
  check_box: 2
  text: 3
  combo_box: 4
  
  #TIPOS DATO
  tipo_dato_numerico: 1
  tipo_dato_texto: 2
 
  #TIPOS DOCUMENTOS
  certificado_nacimiento: 6
  sin_documento: 5
  cedula_identidad: 1

  #SEXOS GANADOS
  sexo_ganado_macho: 1
  sexo_ganado_hembra: 2

  #controles
  control_vacunacion: 1
  control_sales: 2
  control_reconstituyente: 3
  control_interno: 4
  control_externo: 5
  control_antibiotico: 6
  control_peso: 7

  #TIPOS RESOLUCIONES DOCUMENTOS
  tipo_resolucion_control_ganado: 1

  #ESTADOS CELOS
  estado_celo_en_celo_activo: 1
  estado_celo_en_reproduccion: 2
  estado_celo_en_perdido: 3

  #ESTADOS GANADOS
  estado_ganado_activo: 1
  estado_ganado_inactivo: 2
  estado_ganado_en_celo: 3
  estado_ganado_en_reproduccion: 4
  estado_ganado_prenhado: 5
  estado_ganado_en_proceso_venta: 6
  estado_ganado_vendido: 7
  estado_ganado_enfermo: 8
  estado_ganado_muerto: 9

  #ETAPAS GANADOS
  etapa_ganado_vaca: 1
  etapa_ganado_vaquilla: 2
  etapa_ganado_novillo: 3
  etapa_ganado_torito: 4
  etapa_ganado_ternero: 5
  etapa_ganado_ternera: 6
  etapa_ganado_toro: 7

  #TIPOS CONCEPCIONES
  tipo_concepcion_monta_natural: 1
  tipo_concepcion_inseminacion_artificial: 2

  #ESTADOS REPRODUCCIONES
  estado_reproduccion_proceso_fecundacion: 1
  estado_reproduccion_prenhez: 2
  estado_reproduccion_finalizado: 3
  estado_reproduccion_perdido: 4

  #ESPERMAS PROCEDENCIAS
  esperma_local: 1
  esperma_comprada: 2
 
  #ESTADOS ESPERMAS
  estado_esperma_activo: 1
  estado_esperma_inactivo: 2

  #TIPO GANADO
  tipo_ganado_vacuno: 1

  #CLASIFICACIONES APLICACION DE CONTROLES
  clasificacion_por_ganado: 1
  clasificacion_por_lote: 2
  clasificacion_por_potrero: 3
  clasificacion_por_hacienda: 4

  #ESTADOS MOVIMIENTOS (ENTRADA DE GANADOS)
  estado_movimiento_en_proceso: 1
  estado_movimiento_finalizado: 2
 
  #FINALIDADES GANADOS
  finalidad_ganado_no_especificado: 4

  #CLASIFICACION SALIDA GANADO
  clasificacion_salida_por_ganado: 1
  clasificacion_salida_por_lote: 2

  #ESTADO ENFERMEDAD GANADO
  estado_enfermedad_estable: 1
  estado_enfermedad_grave: 2
  estado_enfermedad_critico: 3
  estado_enfermedad_curado: 4
  estado_enfermedad_muerto: 5
  

production:

  #ROLES 
  rol_administrador: 1
  rol_operador: 3
  rol_super: 6
   
  #sistemas
  sistema_RUE: 1
  
  #TIPOS ELEMENTOS INTERFAZ
  radio_button: 1
  check_box: 2
  text: 3
  combo_box: 4
  
  #TIPOS DATO
  tipo_dato_numerico: 1
  tipo_dato_texto: 2
 
  #TIPOS DOCUMENTOS
  certificado_nacimiento: 6
  sin_documento: 5
  cedula_identidad: 1

  #SEXOS GANADOS
  sexo_ganado_macho: 1
  sexo_ganado_hembra: 2

  #controles
  control_vacunacion: 1
  control_sales: 2
  control_reconstituyente: 3
  control_interno: 4
  control_externo: 5
  control_antibiotico: 6
  control_peso: 7

  #TIPOS RESOLUCIONES DOCUMENTOS
  tipo_resolucion_control_ganado: 1

  #ESTADOS CELOS
  estado_celo_en_celo_activo: 1
  estado_celo_en_reproduccion: 2
  estado_celo_en_perdido: 3

  #ESTADOS GANADOS
  estado_ganado_activo: 1
  estado_ganado_inactivo: 2
  estado_ganado_en_celo: 3
  estado_ganado_en_reproduccion: 4
  estado_ganado_prenhado: 5
  estado_ganado_en_proceso_venta: 6
  estado_ganado_vendido: 7
  estado_ganado_enfermo: 8
  estado_ganado_muerto: 9

  #ETAPAS GANADOS
  etapa_ganado_vaca: 1
  etapa_ganado_vaquilla: 2
  etapa_ganado_novillo: 3
  etapa_ganado_torito: 4
  etapa_ganado_ternero: 5
  etapa_ganado_ternera: 6
  etapa_ganado_toro: 7

  #TIPOS CONCEPCIONES
  tipo_concepcion_monta_natural: 1
  tipo_concepcion_inseminacion_artificial: 2

  #ESTADOS REPRODUCCIONES
  estado_reproduccion_proceso_fecundacion: 1
  estado_reproduccion_prenhez: 2
  estado_reproduccion_finalizado: 3
  estado_reproduccion_perdido: 4

  #ESPERMAS PROCEDENCIAS
  esperma_local: 1
  esperma_comprada: 2

  #TIPO GANADO
  tipo_ganado_vacuno: 1

  #CLASIFICACIONES APLICACION DE CONTROLES
  clasificacion_por_ganado: 1
  clasificacion_por_lote: 2
  clasificacion_por_potrero: 3
  clasificacion_por_hacienda: 4

  #ESTADOS MOVIMIENTOS (ENTRADA DE GANADOS)
  estado_movimiento_en_proceso: 1
  estado_movimiento_finalizado: 2

  #FINALIDADES GANADOS
  finalidad_ganado_no_especificado: 4

  #CLASIFICACION SALIDA GANADO
  clasificacion_salida_por_ganado: 1
  clasificacion_salida_por_lote: 2

  #ESTADO ENFERMEDAD GANADO
  estado_enfermedad_estable: 1
  estado_enfermedad_grave: 2
  estado_enfermedad_critico: 3
  estado_enfermedad_curado: 4
  estado_enfermedad_muerto: 5
  
  